import "./globals.css";

export const metadata = {
  title: "Crypto Simulator",
  description: "Generated by Tsunami",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
